id = "gruvbuddy-theme"
name = "Gruvbuddy Theme"
version = "0.0.1"
schema_version = 1
authors = ["Weslei J M Pereira"]
description = "A dark color theme based on gruvbuddy by TJ DeVries"
repository = "https://github.com/weslei/colorbuddy.zed"
